### Numpy
- 데이터를 행렬로 표현
- 행렬 데이터 생성, 수정, 계산등을 빠르게 처리해주는 패키지
- 특징
    - c,c++, 포트란으로 작성
    - 선형대수학을 빠르게 연산
        - 스칼라, 벡터, 매트릭스

In [1]:
import numpy as np

In [2]:
# 행렬 데이터 생성
# ndarray : 한가지 데이터 타입만 값으로 사용 가능

In [3]:
array=np.array([1,2,3])
array,type(array)

(array([1, 2, 3]), numpy.ndarray)

In [4]:
array2=np.array([[1,2,3],[4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
array2.ndim, array2.shape

(2, (2, 3))

In [6]:
# 행렬의 모양(shape) 변경하기

array2.reshape(3,2) 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
array2.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [10]:
# 행렬 데이터 선택 : offset index
array2[1]

array([4, 5, 6])

In [11]:
array2[1][2] #array2[1,2]

6

In [12]:
array2[1][:2]

array([4, 5])

In [13]:
# 데이터 수정

In [14]:
array2[1][2]=10
array2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [15]:
# 브로드 캐스팅
array2[0]=0
array2

array([[ 0,  0,  0],
       [ 4,  5, 10]])

In [16]:
array2[0]=[7,8,9]
array2

array([[ 7,  8,  9],
       [ 4,  5, 10]])

In [18]:
# 조건으로 선택
idx=array2>7
idx

array([[False,  True,  True],
       [False, False,  True]])

In [19]:
array2[idx]

array([ 8,  9, 10])

In [20]:
# 행렬 데이터의 생성 2
data=np.zeros((2,3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
data.astype('int')

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [23]:
# arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [25]:
np.arange(5,10,2)

array([5, 7, 9])

### linspace, logspace 함수
- linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [47]:
# linspace
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [48]:
# logspace
# log10(x1)=2, log10(x2)=3, log10(x3)=4
np.logspace(2,4,3)

array([  100.,  1000., 10000.])

In [49]:
# 30세에 연봉이 $100000이고 60세의 연봉이 $1000000일 떄,
# 연봉이 선형으로 증가, 지수함수로 증가하는 두 경우에서의 40세, 50세 연봉을 출력

In [55]:
np.linspace(100000,1000000,4)[1:3]

array([400000., 700000.])

In [57]:
np.logspace(5,6,4)[1:3]

array([215443.46900319, 464158.88336128])

### Numpy random
- seed : 랜덤값을 설정값
- rand : 균등분포로 랜덤한 값 생성
- randn : 정규분포로 난수를 발생
- randint : 균등분포로 정수값을 생성
- shuffle : 행렬 데이터를 섞어 줌
- choice : 특정 확률로 데이터를 선택

In [58]:
# seed
np.random.seed(1)
result1= np.random.randint(10,100,10)

np.random.seed(1)
result2=np.random.randint(10,100,10)

np.random.seed(2)
result3=np.random.randint(10,100,10)

result1,result2,result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [59]:
np.random.rand(10)

array([0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
       0.52914209, 0.13457995, 0.51357812, 0.18443987, 0.78533515])

In [60]:
np.random.randn(10)

array([-0.0191305 ,  1.17500122, -0.74787095,  0.00902525, -0.87810789,
       -0.15643417,  0.25657045, -0.98877905, -0.33882197, -0.23618403])

In [61]:
# shuffle(제일 앞에 있는 차원만 바뀜)
r=np.random.randint(1,10,(3,4))
r

array([[2, 8, 9, 3],
       [9, 8, 2, 7],
       [9, 6, 4, 1]])

In [62]:
np.random.shuffle(r)
r

array([[9, 8, 2, 7],
       [9, 6, 4, 1],
       [2, 8, 9, 3]])

In [65]:
# choice
np.random.choice(5,10,p=[0.1,0,0.4,0.2,0.3])

array([4, 4, 3, 2, 4, 2, 4, 4, 3, 4])

In [67]:
#unique
numbers, counts=np.unique(r,return_counts=True)
print(numbers)
print(counts)

[1 2 3 4 6 7 8 9]
[1 2 1 1 1 1 2 3]


### 행렬 데이터의 결합
- concatenate

In [69]:
num1=np.random.randint(10,size=(2,3))
num2=np.random.randint(10,size=(3,2))
num3=np.random.randint(10,size=(3,3))

In [74]:
#세로 결합
np.concatenate((num1,num3))

array([[5, 0, 8],
       [6, 5, 1],
       [0, 8, 5],
       [4, 2, 9],
       [7, 1, 9]])

In [77]:
#가로 결합
np.concatenate((num2,num3),axis=1)

array([[7, 4, 0, 8, 5],
       [3, 6, 4, 2, 9],
       [1, 4, 7, 1, 9]])

In [78]:
# c_, r_
np.c_[np.array([1,2,3]),np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [79]:
np.r_[np.array([1,2,3]),np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

### quiz
- 100~130까지 랜덤한 숫자를 가지는 8*8행렬을 만들고,
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz 문자로 변환

In [13]:
array=np.array(np.random.randint(100,131,64)).reshape(8,8)
array

array([[112, 104, 104, 119, 114, 125, 109, 103],
       [121, 106, 122, 114, 107, 100, 116, 123],
       [114, 121, 115, 127, 117, 128, 107, 118],
       [103, 102, 116, 124, 129, 121, 112, 106],
       [104, 117, 126, 116, 107, 115, 116, 113],
       [117, 121, 119, 100, 110, 124, 107, 120],
       [122, 123, 116, 104, 130, 101, 119, 112],
       [118, 117, 112, 103, 102, 113, 111, 101]])

In [29]:
array1=array.astype('str')

In [35]:
array1[array%3==0]='fiz'
array1[array%5==0]='buz'
array1[(array%3==0) & (array%5==0)]='fbz'

array([['112', '104', '104', '119', 'fiz', 'buz', '109', '103'],
       ['121', '106', '122', 'fiz', '107', 'buz', '116', 'fiz'],
       ['fiz', '121', 'buz', '127', 'fiz', '128', '107', '118'],
       ['103', 'fiz', '116', '124', 'fiz', '121', '112', '106'],
       ['104', 'fiz', 'fiz', '116', '107', 'buz', '116', '113'],
       ['fiz', '121', '119', 'buz', 'buz', '124', '107', 'fbz'],
       ['122', 'fiz', '116', '104', 'buz', '101', '119', '112'],
       ['118', 'fiz', '112', '103', 'fiz', '113', 'fiz', '101']],
      dtype='<U11')

### Quiz
- 1~20까지 랜덤한 숫자를 가지는 5*5 행렬 생성
- 최대값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드

In [37]:
array=np.random.randint(1,21,size=(5,5))
array

array([[13,  2, 11,  7,  7],
       [ 1, 18, 16,  5, 15],
       [ 1,  2, 15, 12,  6],
       [19, 14,  4,  2,  8],
       [15,  3,  8, 10,  3]])

In [39]:
array.min(),array.max()

(1, 19)

In [41]:
min_idx=array==array.min()
min_idx

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [42]:
max_idx=array==array.max()
max_idx

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [43]:
result=array.astype('str')

In [45]:
result[min_idx]='MIN'
result[max_idx]='MAX'

In [46]:
result

array([['13', '2', '11', '7', '7'],
       ['MIN', '18', '16', '5', '15'],
       ['MIN', '2', '15', '12', '6'],
       ['MAX', '14', '4', '2', '8'],
       ['15', '3', '8', '10', '3']], dtype='<U11')