#### boolean indexing
- ndarray 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링

- 브로드캐스팅을 활용하여 ndarray로 부터 bool list 얻기
    - 예) 짝수인 경우만 찾아보기

In [1]:
import numpy as np

In [2]:
x=np.random.randint(1,100,size=10)
print(x)

[61 78  5 13  5 39 17 49 80 84]


In [6]:
even_mask = x % 2==0
print(even_mask)

[False  True False False False False False False  True  True]


- bool 리스트를 인덱스로 전달

In [5]:
x[even_mask]

array([78, 80, 84])

In [7]:
x[x%2==0]

array([78, 80, 84])

In [8]:
x[x>30]

array([61, 78, 39, 49, 80, 84])

**다중조건 사용하기**
- 파이썬 논리 연산자인 and,or,not 키워드 사용 불가
- & - and
- | -or

In [9]:
x[(x%2==0) & (x>30)]

array([78, 80, 84])

In [10]:
x[(x<30) | (x>50)]

array([61, 78,  5, 13,  5, 17, 80, 84])

#### 예제) 2019년 7월 서울 평균기온 데이터

In [11]:
temp=np.array([23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
              26.7, 25.1, 25.0, 22.7, 21.9, 23.6,
              24.9, 25.9, 23.8, 24.7, 25.6, 26.9,
              28.6, 28.0, 25.1, 26.7, 28.1, 26.5,
              26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

- 평균기온이 25도를 넘는 날수는?

In [13]:
len(temp[temp>25])#np.sum(temp>25.0)

21

- 평균기온이 25를 넘는 날의 평균 기온은?

In [14]:
temp[temp>25].mean()

26.857142857142858