In [1]:
import numpy as np

#### **브로드캐스팅**
- shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
- 연산되는 두 ndarray가 다른 shape을 갖는 경우 브토드 캐스팅(shape을 맞춤) 후 진행

#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

- shape이 같은 경우의 연산

In [2]:
x=np.arange(15).reshape(3,5)
y=np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.73300478 0.03673108 0.54993371 0.03585559 0.4087128 ]
 [0.66750173 0.12258623 0.62262157 0.00776494 0.24368451]
 [0.98889562 0.25944451 0.57824394 0.4616997  0.73633191]]


In [3]:
x+y

array([[ 0.73300478,  1.03673108,  2.54993371,  3.03585559,  4.4087128 ],
       [ 5.66750173,  6.12258623,  7.62262157,  8.00776494,  9.24368451],
       [10.98889562, 11.25944451, 12.57824394, 13.4616997 , 14.73633191]])

- scaler(상수)와의 연산

In [4]:
x + 2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [5]:
x*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

- shape이 다른 경우 연산

In [26]:
a=np.arange(12).reshape(4,3)
b=np.arange(100,103)
c=np.arange(1000,1004)
d=b.reshape(1,3)
e=c.reshape(4,1)

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)

(4, 3)
(3,)
(4,)
(1, 3)
(4, 1)


In [22]:
a+b #(4,3) + (3,)   b와 a의 열 길이가 같기 떄문에 됨

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [23]:
a+c #(4,3) + (4,) c의 열이 a의 열보다 길기 때문에 안됨

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [24]:
a+d #(4,3) + (1,3)  d를 행방향으로 복사함

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [25]:
a+e # (4,3) + (4,1)  e를 열방향으로 복사함

array([[1000, 1001, 1002],
       [1004, 1005, 1006],
       [1008, 1009, 1010],
       [1012, 1013, 1014]])