In [1]:
import numpy as np

#### np.linalg.inv
- 역행렬을 구할때 사용
- 모든 차원의 값이 같아야 함

In [2]:
x=np.random.rand(3,3)
print(x)

[[0.2290951  0.23205248 0.66865329]
 [0.25833461 0.49039212 0.39021745]
 [0.87381759 0.87899654 0.25711057]]


In [3]:
x @ np.linalg.inv(x) # np.matmul(x,lina.inv(x))

array([[ 1.00000000e+00, -1.54409833e-16, -5.91575770e-17],
       [-1.18708011e-16,  1.00000000e+00, -1.02834730e-17],
       [ 6.58557071e-17,  7.14305324e-17,  1.00000000e+00]])

#### np.linalg.solve
- Ax=B 형태의 선형대수식 솔루션을 제공
- 예제) 호랑이와 홍합의 합 : 25, 호랑이 다리와 홍합 다리의 합은 64
    - X + Y =25
    - 2X + 4Y = 64
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$
    
    

In [4]:
A = np.array([[1,1],[2,4]])
B=np.array([25,64])

x=np.linalg.solve(A,B)
print(x)

[18.  7.]
