In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
- 0,1사이의 분포로 랜덤한 ndarray 생성

In [2]:
np.random.rand(2,3)

array([[0.31609368, 0.58648207, 0.85882445],
       [0.92149395, 0.79996426, 0.72018953]])

#### randn 함수
- n:normal distribution(정규분포)
- 정규분포로 샘플링된 랜덤 ndarray 생성

In [3]:
np.random.randn(3,4)

array([[-0.59612818,  0.41492966, -0.83819543,  1.30151673],
       [ 1.3172903 ,  0.0603675 , -0.10277536, -0.03266223],
       [-0.78434417, -0.28114789,  0.47593822,  0.22905176]])

#### randint 함수
- 특정 정수 사이에서 랜덤하게 샘플링

In [5]:
np.random.randint(1,100,size=(3,5))

array([[ 8, 65, 64, 27, 68],
       [33, 67,  4, 89, 68],
       [22, 33, 76, 27,  6]])

In [6]:
np.random.randint(1,100,size=(3,5,2))

array([[[60, 61],
        [36, 15],
        [30, 52],
        [41, 33],
        [17, 45]],

       [[97, 56],
        [69, 70],
        [50, 85],
        [35,  9],
        [27, 32]],

       [[96,  6],
        [21, 55],
        [22, 81],
        [89,  3],
        [44, 45]]])

#### seed 함수
- 랜덤한 값을 동일하게 다시 생성하고 할때 사용

In [7]:
np.random.seed(100)
np.random.randn(3,4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

In [8]:
np.random.seed(100)
np.random.randn(3,4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

In [9]:
np.random.randn(3,4)

array([[-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574]])

#### choice
- 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
- 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [10]:
np.random.choice(100,size=(3,4))

array([[39, 38, 44, 18],
       [64, 56, 34, 53],
       [74, 17, 72, 13]])

In [11]:
x = np.array([1,2,3,1.5,2,6,4.9])
np.random.choice(x,size=(2,2))

array([[3. , 4.9],
       [2. , 6. ]])

#### 확률분포에 따른 ndarray 생성
- uniform
- normal 등등

In [12]:
np.random.uniform(1.0,3.0,size=(4,5))

array([[1.23660567, 2.72589134, 1.14973376, 2.65018972, 2.67226363],
       [1.15078982, 1.02280158, 1.09684114, 1.71424542, 2.33138675],
       [1.02277922, 1.21583553, 2.8020262 , 2.58975752, 2.62292196],
       [2.28055611, 2.24955902, 1.29101502, 2.1404318 , 1.130225  ]])

In [13]:
np.random.normal(size=(3,4))#np.random.randn과 동일

array([[-1.0411337 , -0.68659935, -2.55944758,  0.94631055],
       [ 0.79067165,  0.68000189,  0.71660582,  0.47770485],
       [-0.66623993,  0.08448008, -0.33876049,  0.70592118]])