In [1]:
import numpy as np

#### np.array 함수로 생성하기

In [2]:
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [4]:
y=np.array([[2,3,4],[1,2,5]])
print(y)

[[2 3 4]
 [1 2 5]]


#### np.arange 함수로 생성하기

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

#### np.ones, np.zeros로 생성하기

In [8]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#### np.empty, np.full로 생성하기

In [11]:
np.empty((3,4))

array([[1.14860537e-311, 2.86558075e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.08221785e-312, 8.60952352e-072, 7.73900860e-091,
        2.65066734e-032],
       [1.26138664e-076, 1.86426637e+160, 6.48224659e+170,
        5.82471487e+257]])

In [12]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### np.eye로 생성하기
- 단위 행렬 생성

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### np.linspace로 생성하기 (구간 시작점,구간 끝점, 구간 내 숫자개수)-동일 간격

In [15]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [16]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

#### reshape 함수 활용
- ndarray의 형태, 차원을 바꾸기 위해 사용

In [17]:
x=np.arange(1,16)
print(x)

x.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


(15,)

In [18]:
x.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])