In [1]:
import numpy as np

#### **numpy documentation**
- [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
- numpy에서 제공되는 함수등에 대한 문서

In [2]:
x=np.arange(15).reshape(3,5)
y=np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.6267314  0.58731419 0.59315036 0.24244143 0.46190906]
 [0.04490486 0.0598036  0.68395831 0.9903198  0.86495658]
 [0.19604347 0.20940951 0.04401198 0.77361284 0.59606741]]


#### **연산 함수**
- add,subtract, multiply, divide

In [3]:
np.add(x,y)

array([[ 0.6267314 ,  1.58731419,  2.59315036,  3.24244143,  4.46190906],
       [ 5.04490486,  6.0598036 ,  7.68395831,  8.9903198 ,  9.86495658],
       [10.19604347, 11.20940951, 12.04401198, 13.77361284, 14.59606741]])

In [6]:
np.subtract(x,y)

array([[-0.6267314 ,  0.41268581,  1.40684964,  2.75755857,  3.53809094],
       [ 4.95509514,  5.9401964 ,  6.31604169,  7.0096802 ,  8.13504342],
       [ 9.80395653, 10.79059049, 11.95598802, 12.22638716, 13.40393259]])

In [8]:
np.multiply(x,y)

array([[ 0.        ,  0.58731419,  1.18630071,  0.72732429,  1.84763624],
       [ 0.22452431,  0.35882162,  4.78770814,  7.92255839,  7.78460918],
       [ 1.96043473,  2.3035046 ,  0.52814379, 10.05696698,  8.34494381]])

In [9]:
np.divide(x,y)

array([[  0.        ,   1.70266616,   3.37182635,  12.37412275,
          8.65971323],
       [111.34651977, 100.32840135,  10.23454198,   8.07819859,
         10.40514663],
       [ 51.00909426,  52.52865562, 272.6530191 ,  16.80427114,
         23.48727618]])

#### **통계 함수**
- 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [10]:
print(y)

[[0.6267314  0.58731419 0.59315036 0.24244143 0.46190906]
 [0.04490486 0.0598036  0.68395831 0.9903198  0.86495658]
 [0.19604347 0.20940951 0.04401198 0.77361284 0.59606741]]


In [11]:
np.mean(y)#y.mean()

0.4649756537174427

In [12]:
np.max(y)

0.990319798199412

In [13]:
np.argmax(x)#가장 큰값의 인덱스

14

In [14]:
np.var(y),np.median(y),np.std(y)

(0.09059537992769379, 0.5873141915280646, 0.3009906641869375)

#### **집계 함수**
- 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [15]:
print(y)

[[0.6267314  0.58731419 0.59315036 0.24244143 0.46190906]
 [0.04490486 0.0598036  0.68395831 0.9903198  0.86495658]
 [0.19604347 0.20940951 0.04401198 0.77361284 0.59606741]]


In [17]:
np.sum(y)

6.9746348057616405

In [19]:
np.sum(y,axis=0)

array([0.86767973, 0.85652731, 1.32112064, 2.00637407, 1.92293305])

In [18]:
np.cumsum(y)

array([0.6267314 , 1.21404559, 1.80719595, 2.04963738, 2.51154644,
       2.5564513 , 2.6162549 , 3.30021321, 4.29053301, 5.15548958,
       5.35153305, 5.56094256, 5.60495455, 6.37856739, 6.97463481])

#### **any,all함수**
- any : 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
- all : 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [22]:
z=np.random.randn(10)
print(z)

[ 2.96704297 -0.66845149 -0.12281887  1.96725409 -0.77858985  0.45388274
 -0.07360737 -0.0476611   0.51125738 -1.65641402]


In [23]:
z>0

array([ True, False, False,  True, False,  True, False, False,  True,
       False])

In [24]:
np.any(z>0)

True

In [25]:
np.all(z>0)

False

In [26]:
np.all(z!=0)

True

#### **where 함수**
- 조건에 따라 선별적으로 값을 선택 가능
- 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [27]:
z=np.random.randn(10)
print(z)

[ 0.56164067  2.89992728 -0.25003737  0.48708724 -0.25016838  0.91991428
  0.92842125 -1.45273164  1.09578021 -0.62659549]


In [28]:
np.where(z>0,z,0)#where(조건,조건에 맞을때 반환값,조건과 다를때 반환값)

array([0.56164067, 2.89992728, 0.        , 0.48708724, 0.        ,
       0.91991428, 0.92842125, 0.        , 1.09578021, 0.        ])